# Jenkins 데이터용 PersistentVolume 설정 (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/home/ec2-user/jenkins_home"  # Jenkins 데이터를 저장할 디렉토리

---

# Jenkins 데이터용 PersistentVolumeClaim 설정 (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual

---

# Jenkins Deployment 설정
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-react
  template:
    metadata:
      labels:
        app: jenkins-react
    spec:
      initContainers:
      - name: volume-permissions-fix
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
        volumeMounts:
        - name: jenkins-data-volume
          mountPath: /var/jenkins_home
      containers:
      - name: jenkins
        image: kangwoobin/jenkins-with-docker:latest
        env:
        - name: JENKINS_HOME
          value: /var/jenkins_home
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-data-volume
          mountPath: /var/jenkins_home
        - name: docker-sock  # Docker 소켓 볼륨 마운트
          mountPath: /var/run/docker.sock
      volumes:
      - name: jenkins-data-volume
        persistentVolumeClaim:
          claimName: jenkins-data-pvc
      - name: docker-sock  # Docker 소켓 볼륨 정의
        hostPath:
          path: /var/run/docker.sock

---

# Jenkins Service 설정
apiVersion: v1
kind: Service
metadata:
  name: jenkins-react-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32002  # 외부 접속용 NodePort
    - name: agent
      port: 50000
      targetPort: 50000
      nodePort: 32003
  selector:
    app: jenkins-react
