apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-nginx
  template:
    metadata:
      labels:
        app: vite-nginx
    spec:
      nodeSelector:
        node-role: frontend
      containers:
      - name: vite-nginx
        image: kangwoobin/react-app:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vite-nginx-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # NodePort 지정 (필요에 따라 포트 번호 변경)
  selector:
    app: vite-nginx

