apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-nginx
  template:
    metadata:
      labels:
        app: vite-nginx
    spec:
      containers:
      - name: vite-nginx
        image: kangwoobin/react-app:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vite-nginx-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: vite-nginx
